"""Unified RAG ingestion pipeline: parse -> chunk -> embed -> store.

This is the single entry point for populating the Milvus knowledge base.  It
supports two complementary document sources and embeds them with BGE-M3
(dense + sparse) before inserting into the ``tft_documents_v2`` collection.

Sources
-------
* ``structured`` — single-fact documents templated from ``data/tft.db``
  (champion profiles, trait guides, item info, synergy pairs).
* ``corpus`` — real multi-section Markdown strategy guides under
  ``data/corpus`` (generated by ``scripts/generate_corpus.py``), parsed and
  chunked by the heading-aware :class:`MarkdownSplitter`.  Every chunk carries
  provenance metadata (source file, title, heading path) for later citation.

Usage::

    python scripts/ingest_milvus.py --source all     # both sources
    python scripts/ingest_milvus.py --source corpus --recreate
    python scripts/ingest_milvus.py --source structured --chunk-size 600

Prerequisites:
    - Milvus standalone running (``docker compose up -d etcd minio milvus``)
    - For the corpus source, run ``scripts/generate_corpus.py`` first.
"""
from __future__ import annotations

import argparse
import sqlite3
import sys
import time
from pathlib import Path

# Ensure project root is on sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Maps corpus subdirectories to a doc_type tag used for filtering/metadata.
CORPUS_DOC_TYPES = {
    "comps": "comp_guide",
    "traits": "trait_guide",
    "meta": "meta_overview",
}


# ---------------------------------------------------------------------------
# Source 1: structured documents from tft.db
# ---------------------------------------------------------------------------

def generate_structured_documents(db_path: str) -> list[dict]:
    """Generate single-fact knowledge documents from tft.db.

    Each record is already a self-contained fact (no chunking needed).  Every
    record is tagged with ``source='tft.db'`` plus a human-readable ``title``
    so retrieval results can be cited uniformly alongside corpus chunks.
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    docs: list[dict] = []

    champions = conn.execute(
        "SELECT id, name_zh, name_en, cost FROM champions"
    ).fetchall()

    for champ in champions:
        traits = [
            r["name_zh"]
            for r in conn.execute(
                "SELECT t.name_zh FROM champion_traits ct "
                "JOIN traits t ON ct.trait_id = t.id WHERE ct.champion_id = ?",
                (champ["id"],),
            ).fetchall()
        ]
        trait_str = "、".join(traits) if traits else "未知"
        content = (
            f"{champ['name_zh']}（{champ['name_en']}）是 TFT Set 17 中的 "
            f"{champ['cost']} 费英雄。羁绊：{trait_str}。"
        )
        if champ["cost"] >= 4:
            content += " 作为高费卡，适合作为核心主C或关键副C。"
        elif champ["cost"] <= 2:
            content += " 作为低费卡，适合前期过渡或追三星。"
        docs.append({
            "id": f"champ_{champ['id']}",
            "content": content,
            "doc_type": "champion_profile",
            "champion_id": champ["id"],
            "source": "tft.db",
            "title": f"{champ['name_zh']} 英雄档案",
        })

    traits = conn.execute("SELECT id, name_zh, name_en FROM traits").fetchall()
    for trait in traits:
        members = conn.execute(
            "SELECT c.name_zh, c.cost FROM champion_traits ct "
            "JOIN champions c ON ct.champion_id = c.id WHERE ct.trait_id = ? "
            "ORDER BY c.cost DESC",
            (trait["id"],),
        ).fetchall()
        if not members:
            continue
        member_str = "、".join(f"{m['name_zh']}({m['cost']}费)" for m in members)
        content = (
            f"羁绊「{trait['name_zh']}」（{trait['name_en']}）共有 {len(members)} 个英雄："
            f"{member_str}。"
        )
        count = len(members)
        if count >= 6:
            content += " 该羁绊英雄数量充足，容易凑齐高激活等级。"
        elif count <= 3:
            content += " 该羁绊英雄较少，需要转职纹章或特定条件才能高激活。"
        docs.append({
            "id": f"trait_{trait['id']}",
            "content": content,
            "doc_type": "trait_guide",
            "champion_id": "",
            "source": "tft.db",
            "title": f"{trait['name_zh']} 羁绊",
        })

    items = conn.execute(
        "SELECT id, name_zh, name_en FROM items WHERE name_zh != '' LIMIT 200"
    ).fetchall()
    for item in items:
        content = f"装备「{item['name_zh']}」（{item['name_en']}）是 TFT Set 17 中的可合成装备。"
        docs.append({
            "id": f"item_{item['id']}",
            "content": content,
            "doc_type": "item_info",
            "champion_id": "",
            "source": "tft.db",
            "title": f"{item['name_zh']} 装备",
        })

    conn.close()
    return docs


# ---------------------------------------------------------------------------
# Source 2: real Markdown corpus (parse + chunk)
# ---------------------------------------------------------------------------

def load_corpus_chunks(corpus_dir: str, chunk_size: int, chunk_overlap: int) -> list[dict]:
    """Parse and chunk the Markdown corpus into provenance-tagged records."""
    from api.services.rag.chunker import MarkdownSplitter

    splitter = MarkdownSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    corpus_root = Path(corpus_dir)
    if not corpus_root.exists():
        print(f"警告：语料目录不存在 {corpus_root}，请先运行 scripts/generate_corpus.py")
        return []

    records: list[dict] = []
    for subdir, doc_type in CORPUS_DOC_TYPES.items():
        sub = corpus_root / subdir
        if not sub.exists():
            continue
        for path in sorted(sub.rglob("*.md")):
            for chunk in splitter.split_file(path, base_metadata={"doc_type": doc_type}):
                records.append({
                    "id": f"corpus::{chunk.metadata['source']}::{chunk.metadata['chunk_index']}",
                    "content": chunk.content,
                    "doc_type": chunk.metadata.get("doc_type", doc_type),
                    "champion_id": "",
                    "source": chunk.metadata.get("source", path.name),
                    "title": chunk.metadata.get("title", ""),
                })
    return records


# ---------------------------------------------------------------------------
# Embed + insert
# ---------------------------------------------------------------------------

def embed_and_insert(
    docs: list[dict],
    batch_size: int,
    milvus_host: str,
    milvus_port: str,
    model_path: str,
    recreate: bool,
) -> None:
    from api.services.rag.embedding import BGEEmbedding
    from api.services.rag.engine import MilvusStore

    from api.config import get_settings

    s = get_settings()
    print(f"[1/3] 加载 BGE-M3 模型: {model_path} (device={s.DEVICE}, fp16={s.USE_FP16})")
    embedding = BGEEmbedding(
        model_name=model_path, device=s.DEVICE, use_fp16=s.USE_FP16
    )

    print(f"[2/3] 连接 Milvus ({milvus_host}:{milvus_port})...")
    store = MilvusStore(host=milvus_host, port=milvus_port)
    store.connect()
    if recreate:
        store.drop_collection()
    store.ensure_collection()

    print(f"[3/3] 编码并插入 {len(docs)} 条记录（batch_size={batch_size}）...")
    total_inserted = 0
    start = time.time()

    for i in range(0, len(docs), batch_size):
        batch = docs[i : i + batch_size]
        texts = [d["content"] for d in batch]
        encoded = embedding.encode(texts, batch_size=batch_size)

        records = []
        for j, doc in enumerate(batch):
            records.append({
                "id": doc["id"],
                "content": doc["content"],
                "dense": encoded["dense"][j].tolist(),
                "sparse": encoded["sparse"][j],
                "doc_type": doc.get("doc_type", ""),
                "champion_id": doc.get("champion_id", ""),
                "source": doc.get("source", ""),
                "title": doc.get("title", ""),
            })
        total_inserted += store.insert(records)
        print(f"  进度: {total_inserted}/{len(docs)} ({time.time() - start:.1f}s)")

    elapsed = time.time() - start
    print(f"\n完成！共插入 {total_inserted} 条记录，耗时 {elapsed:.1f}s")
    print(f"Collection: {MilvusStore.COLLECTION_NAME}")
    print("doc_type 分布:")
    counts: dict[str, int] = {}
    for d in docs:
        counts[d["doc_type"]] = counts.get(d["doc_type"], 0) + 1
    for dtype, count in sorted(counts.items()):
        print(f"  {dtype}: {count}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    from api.config import get_settings

    settings = get_settings()
    parser = argparse.ArgumentParser(description="Unified RAG ingestion pipeline")
    parser.add_argument("--source", choices=["structured", "corpus", "all"], default="all")
    parser.add_argument("--db", default="data/tft.db")
    parser.add_argument("--corpus-dir", default="data/corpus")
    parser.add_argument("--chunk-size", type=int, default=600)
    parser.add_argument("--chunk-overlap", type=int, default=80)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--milvus-host", default=settings.MILVUS_HOST)
    parser.add_argument("--milvus-port", default=settings.MILVUS_PORT)
    parser.add_argument("--model", default=settings.EMBEDDING_MODEL)
    parser.add_argument(
        "--recreate", action="store_true",
        help="Drop and recreate the collection before ingesting (idempotent).",
    )
    args = parser.parse_args()

    docs: list[dict] = []
    if args.source in ("structured", "all"):
        db_path = Path(args.db)
        if not db_path.exists():
            print(f"错误：数据库文件不存在 {db_path}")
            sys.exit(1)
        structured = generate_structured_documents(str(db_path))
        print(f"[structured] 生成 {len(structured)} 条结构化记录")
        docs.extend(structured)

    if args.source in ("corpus", "all"):
        corpus = load_corpus_chunks(args.corpus_dir, args.chunk_size, args.chunk_overlap)
        print(f"[corpus] 解析+切分得到 {len(corpus)} 条 chunk")
        docs.extend(corpus)

    if not docs:
        print("没有记录可插入，退出。")
        sys.exit(0)

    embed_and_insert(
        docs, args.batch_size, args.milvus_host, args.milvus_port,
        args.model, args.recreate,
    )


if __name__ == "__main__":
    main()
